---
namespace: staging
replicas:
  - name: nginx-deployment
    count: 1
images:
  - name: iskliarov/nginx
    newName: iskliarov/nginx-private
    newTag: v0.0.1
resources:
  - ../../../my-app-base
patches:
  - target:
      kind: Deployment
    path: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: dockerconfigjson }]


      
    